
import { RdsData } from './types';

// ODA AID Mapping
export const ODA_MAP: Record<string, string> = {
    "CD46": "TMC (Traffic Message Channel)",
    "4BD7": "Radiotext+",
    "0093": "DAB Cross-Referencing",
    "CD9E": "EWS (Emergency Warning System)",
    "C737": "UMC (Utility Message Channel)",
    "E1C1": "Action Code",
    "C4D4": "eEAS",
    "CD47": "TMC (Traffic Message Channel)",
    "48D8": "Radiotext+",
    "4400": "RDS-Light",
    "A112": "NL Alert System",
    "ABCF": "RF Power Monitoring",
    "E411": "Beacon Downlink",
    "E123": "APS Gateway",
    "C3C3": "Traffic Plus by NAVTEQ",
    "C3B0": "iTunes Tagging",
    "C3A1": "Personal Radio Service",
    "6A7A": "Warning Receiver",
    "6365": "RDS2",
    "5757": "Personal Weather Station",
    "7373": "Enhanced Early Warning System",
    "CB73": "CITIBUS 1",
    "4C59": "CITIBUS 2",
    "CC21": "CITIBUS 3",
    "1DC2": "CITIBUS 4",
    "4AA1": "RASANT",
    "A911": "Data FM Messaging",
    "FF7F": "RFT Station Logo",
    "FF80": "RFT Slideshow",
    "CD19": "TokenMe",
    "FF70": "Internet Connection",
    "FF81": "RFT Journaline",
    "BE22": "Push-Ad",
    "ABCE": "Fleximax by Worldcast Systems",
    "C563": "ID Logic",
    "E911": "EAS Open Protocol",
    "C350": "NRSC Title and Artist",
    "C549": "Smart Grid Broadcast Channel",
    "C6A7": "Veil Enabled Interactive Device",
    "1BDA": "ELECTRABEL-DSM",
    "0F87": "ELECTRABEL-DSM",
    "0E2C": "ELECTRABEL-DSM",
    "1D47": "ELECTRABEL-DSM",
    "4BA2": "ELECTRABEL-DSM",
    "E5D7": "ELECTRABEL-DSM",
    "0C24": "ELECTRABEL-DSM",
    "4AB7": "ELECTRABEL-DSM",
    "1CB1": "ELECTRABEL-DSM",
    "4D9A": "ELECTRABEL-DSM",
    "E319": "ELECTRABEL-DSM",
    "0E31": "ELECTRABEL-DSM",
    "CB97": "ELECTRABEL-DSM",
    "E440": "ELECTRABEL-DSM",
    "4D95": "ELECTRABEL-DSM",
    "1E8F": "ELECTRABEL-DSM",
    "0D8B": "ELECTRABEL-DSM",
    "E4A6": "ELECTRABEL-DSM",
    "1C5E": "ELECTRABEL-DSM",
    "0BCB": "Leisure and Practical Info for Drivers",
    "4D87": "RCS (Radio Commerce System)",
    "0D45": "TMC ISO 14819-1 (For testing use only)",
    "0CC1": "WiPla Broadcast Control Signal",
    "1C68": "ITIS In-Vehicle Database",
    "6552": "eRT (Enhanced RadioText)",
    "125F": "I-FM RDS for Fixed and Mobile Devices",
    "50DD": "Disaster Warning System",
    "6363": "Hybradio RDS-Net (For testing use only)",
    "4BD8": "Radiotext+ for eRT"
};

export const TMC_EVENT_MAP: Record<number, string> = {
    1: "Traffic problem",
    2: "Queuing traffic - Danger of stationary traffic!",
    11: "Overheight warning system triggered",
    12: "Accident(s) - Traffic being directed around the area",
    16: "Closed - rescue and recovery work in progress",
    20: "Service area overcrowded",
    22: "Service area - fuel station closed",
    23: "Service area - restaurant closed",
    24: "Bridge closed",
    25: "Tunnel closed",
    26: "Bridge blocked",
    27: "Tunnel blocked",
    28: "Road closed intermittently",
    36: "Fuel station reopened",
    37: "Restaurant reopened",
    39: "Reopening of bridge expected",
    40: "Smog alert ended",
    41: "Overtaking lane(s) closed",
    42: "Overtaking lane(s) blocked",
    43: "Overtaking lane(s) restricted",
    44: "Fast lane closed",
    45: "Fast lane blocked",
    46: "Overtaking lane(s) reopened",
    47: "Traffic congestion, average speed of 100 km/h",
    48: "Traffic congestion, average speed of 90 km/h",
    49: "Traffic congestion, average speed of 80 km/h",
    50: "Traffic congestion, average speed of 110 km/h",
    51: "Roadworks - overtaking lane(s) closed",
    52: "Roadworks on the hard shoulder",
    53: "Roadworks in the emergency lane",
    55: "Traffic problem expected",
    56: "Traffic congestion expected",
    57: "Normal traffic expected",
    61: "Object(s) on roadway",
    62: "Burst pipe(s)",
    63: "Object(s) on the road - Danger!",
    64: "Burst pipe - Danger!",
    70: "Traffic congestion, average speed of 10 km/h",
    71: "Traffic congestion, average speed of 20 km/h",
    72: "Traffic congestion, average speed of 30 km/h",
    73: "Traffic congestion, average speed of 40 km/h",
    74: "Traffic congestion, average speed of 50 km/h",
    75: "Traffic congestion, average speed of 60 km/h",
    76: "Traffic congestion, average speed of 70 km/h",
    80: "Heavy traffic has to be expected",
    81: "Traffic congestion has to be expected",
    82: "Roadworks - Heavy traffic has to be expected",
    83: "Closure ahead - Heavy traffic expected",
    84: "Major event - Heavy traffic has to be expected",
    85: "Sports meeting - Heavy traffic has to be expected",
    86: "Fair - Heavy traffic has to be expected",
    87: "Evacuation - Heavy traffic has to be expected",
    88: "Traffic congestion forecast withdrawn",
    89: "[Message cancelled]",
    91: "Delays for cars",
    101: "Stationary traffic",
    102: "Stationary traffic for 1 km",
    103: "Stationary traffic for 2 km",
    104: "Stationary traffic for 4 km",
    105: "Stationary traffic for 6 km",
    106: "Stationary traffic for 10 km",
    107: "Stationary traffic expected",
    108: "Queuing traffic",
    109: "Queuing traffic for 1 km",
    110: "Queuing traffic for 2 km",
    111: "Queuing traffic for 4 km",
    112: "Queuing traffic for 6 km",
    113: "Queuing traffic for 10 km",
    114: "Queuing traffic expected",
    115: "Slow traffic",
    116: "Slow traffic for 1 km",
    117: "Slow traffic for 2 km",
    118: "Slow traffic for 4 km",
    119: "Slow traffic for 6 km",
    120: "Slow traffic for 10 km",
    121: "Slow traffic expected",
    122: "Heavy traffic",
    123: "Heavy traffic expected",
    124: "Traffic flowing freely",
    125: "Traffic building up",
    126: "No problems to report",
    127: "Traffic congestion cleared",
    128: "[Message cancelled]",
    129: "Stationary traffic for 3 km",
    130: "Danger of stationary traffic!",
    131: "Queuing traffic for 3 km",
    132: "Danger of queuing traffic!",
    133: "Long queues",
    134: "Slow traffic for 3 km",
    135: "Traffic easing",
    136: "Traffic congestion",
    137: "Traffic lighter than normal",
    138: "Queuing traffic - Approach with care",
    139: "Queuing traffic around a bend in the road",
    140: "Queuing traffic over the crest of a hill",
    141: "All accidents cleared - no problems to report",
    142: "Traffic heavier than normal",
    143: "Traffic very much heavier than normal",
    200: "Multi vehicle pile up - Delays",
    201: "Accident(s)",
    202: "Serious accident(s)",
    203: "Multi-vehicle accident",
    204: "Accident involving heavy lorr(y/ies)",
    205: "Accident(s) involving hazardous materials",
    206: "Fuel spillage accident(s)",
    207: "Chemical spillage accident(s)",
    208: "Vehicles slowing to look at accident(s)",
    209: "Accident(s) in the opposing lanes",
    210: "Shed load(s)",
    211: "Broken down vehicle(s)",
    212: "Broken down heavy lorr(y/ies)",
    213: "Vehicle fire(s)",
    214: "Incident(s)",
    215: "Accident(s) - Stationary traffic",
    216: "Accident(s) - Stationary traffic for 1 km",
    217: "Accident(s) - Stationary traffic for 2 km",
    218: "Accident(s) - Stationary traffic for 4 km",
    219: "Accident(s) - Stationary traffic for 6 km",
    220: "Accident(s) - Stationary traffic for 10 km",
    221: "Accident(s) - Danger of stationary traffic!",
    222: "Accident(s) - Queuing traffic",
    223: "Accident(s) - Queuing traffic for 1 km",
    224: "Accident(s) - Queuing traffic for 2 km",
    225: "Accident(s) - Queuing traffic for 4 km",
    226: "Accident(s) - Queuing traffic for 6 km",
    227: "Accident(s) - Queuing traffic for 10 km",
    228: "Accident(s) - Danger of queuing traffic!",
    229: "Accident(s) - Slow traffic",
    230: "Accident(s) - Slow traffic for 1 km",
    231: "Accident(s) - Slow traffic for 2 km",
    232: "Accident(s) - Slow traffic for 4 km",
    233: "Accident(s) - Slow traffic for 6 km",
    234: "Accident(s) - Slow traffic for 10 km",
    235: "Accident(s) - Slow traffic expected",
    236: "Accident(s) - Heavy traffic",
    237: "Accident(s) - Heavy traffic expected",
    238: "Accident(s) - Traffic flowing freely",
    239: "Accident(s) - Traffic building up",
    240: "Road closed due to accident(s)",
    241: "Accident(s) - Right lane blocked",
    242: "Accident(s) - Centre lane blocked",
    243: "Accident(s) - Left lane blocked",
    244: "Accident(s) - Hard shoulder blocked",
    245: "Accident(s) - Two lanes blocked",
    246: "Accident(s) - Three lanes blocked",
    247: "Accident - Delays",
    248: "Accident - Delays expected",
    249: "Accident - Long delays",
    250: "Vehicles slowing to look at accident(s)",
    251: "Vehicles slowing to look at accident(s) - Stationary traffic for 1 km",
    252: "Vehicles slowing to look at accident(s) - Stationary traffic for 2 km",
    253: "Vehicles slowing to look at accident(s) - Stationary traffic for 4 km",
    254: "Vehicles slowing to look at accident(s) - Stationary traffic for 6 km",
    255: "Vehicles slowing to look at accident(s) - Stationary traffic for 10 km",
    256: "Vehicles slowing to look at accident(s) - Danger of stationary traffic!",
    257: "Vehicles slowing to look at accident(s) - Queuing traffic",
    258: "Vehicles slowing to look at accident(s) - Queuing traffic for 1 km",
    259: "Vehicles slowing to look at accident(s) - Queuing traffic for 2 km",
    260: "Vehicles slowing to look at accident(s) - Queuing traffic for 4 km",
    261: "Vehicles slowing to look at accident(s) - Queuing traffic for 6 km",
    262: "Vehicles slowing to look at accident(s) - Queuing traffic for 10 km",
    263: "Vehicles slowing to look at accident(s) - Danger of queuing traffic!",
    264: "Vehicles slowing to look at accident(s) - Slow traffic",
    265: "Vehicles slowing to look at accident(s) - Slow traffic for 1 km",
    266: "Vehicles slowing to look at accident(s) - Slow traffic for 2 km",
    267: "Vehicles slowing to look at accident(s) - Slow traffic for 4 km",
    268: "Vehicles slowing to look at accident(s) - Slow traffic for 6 km",
    269: "Vehicles slowing to look at accident(s) - Slow traffic for 10 km",
    270: "Vehicles slowing to look at accident(s) - Slow traffic expected",
    271: "Vehicles slowing to look at accident(s) - Heavy traffic",
    272: "Vehicles slowing to look at accident(s) - Heavy traffic expected",
    274: "Vehicles slowing to look at accident(s) - Traffic building up",
    275: "Vehicles slowing to look at accident - Delays",
    276: "Vehicles slowing to look at accident - Delays expected",
    277: "Vehicles slowing to look at accident - Long delays",
    278: "Shed load(s) - Stationary traffic",
    279: "Shed load(s) - Stationary traffic for 1 km",
    280: "Shed load(s) - Stationary traffic for 2 km",
    281: "Shed load(s) - Stationary traffic for 4 km",
    282: "Shed load(s) - Stationary traffic for 6 km",
    283: "Shed load(s) - Stationary traffic for 10 km",
    284: "Shed load(s) - Danger of stationary traffic!",
    285: "Shed load(s) - Queuing traffic",
    286: "Shed load(s) - Queuing traffic for 1 km",
    287: "Shed load(s) - Queuing traffic for 2 km",
    288: "Shed load(s) - Queuing traffic for 4 km",
    289: "Shed load(s) - Queuing traffic for 6 km",
    290: "Shed load(s) - Queuing traffic for 10 km",
    291: "Shed load(s) - Danger of queuing traffic!",
    292: "Shed load(s) - Slow traffic",
    293: "Shed load(s) - Slow traffic for 1 km",
    294: "Shed load(s) - Slow traffic for 2 km",
    295: "Shed load(s) - Slow traffic for 4 km",
    296: "Shed load(s) - Slow traffic for 6 km",
    297: "Shed load(s) - Slow traffic for 10 km",
    298: "Shed load(s) - Slow traffic expected",
    299: "Shed load(s) - Heavy traffic",
    300: "Shed load(s) - Heavy traffic expected",
    301: "Shed load(s) - Traffic flowing freely",
    302: "Shed load(s) - Traffic building up",
    303: "Blocked by shed load(s)",
    304: "Shed load(s) - Right lane blocked",
    305: "Shed load(s) - Centre lane blocked",
    306: "Shed load(s) - Left lane blocked",
    307: "Shed load(s) - Hard shoulder blocked",
    308: "Shed load(s) - Two lanes blocked",
    309: "Shed load(s) - Three lanes blocked",
    310: "Shed load - Delays",
    311: "Shed load - Delays expected",
    312: "Shed load - Long delays",
    313: "Broken down vehicle(s) - Stationary traffic",
    314: "Broken down vehicle(s) - Danger of stationary traffic!",
    315: "Broken down vehicle(s) - Queuing traffic",
    316: "Broken down vehicle(s) - Danger of queuing traffic!",
    317: "Broken down vehicle(s) - Slow traffic",
    318: "Broken down vehicle(s) - Slow traffic expected",
    319: "Broken down vehicle(s) - Heavy traffic",
    320: "Broken down vehicle(s) - Heavy traffic expected",
    321: "Broken down vehicle(s) - Traffic flowing freely",
    322: "Broken down vehicle(s) - Traffic building up",
    323: "Blocked by broken down vehicle(s)",
    324: "Broken down vehicle(s) - Right lane blocked",
    325: "Broken down vehicle(s) - Centre lane blocked",
    326: "Broken down vehicle(s) - Left lane blocked",
    327: "Broken down vehicle(s) - Hard shoulder blocked",
    328: "Broken down vehicle(s) - Two lanes blocked",
    329: "Broken down vehicle(s) - Three lanes blocked",
    330: "Broken down vehicle - Delays",
    331: "Broken down vehicle - Delays expected",
    332: "Broken down vehicle - Long delays",
    333: "Accident cleared",
    334: "[Message cancelled]",
    335: "Accident involving bus(es)",
    336: "Oil spillage accident(s)",
    337: "Overturned vehicle(s)",
    338: "Overturned heavy lorr(y/ies)",
    339: "Jackknifed trailer(s)",
    340: "Jackknifed caravan(s)",
    341: "Jackknifed articulated lorr(y/ies)",
    342: "Vehicle(s) spun around",
    343: "Earlier accident(s)",
    344: "Accident investigation work",
    345: "Secondary accident(s)",
    346: "Broken down bus(es)",
    347: "Overheight vehicle(s)",
    348: "Accident(s) - Stationary traffic for 3 km",
    349: "Accident(s) - Queuing traffic for 3 km",
    350: "Accident(s) - Slow traffic for 3 km",
    351: "Accident(s) in roadworks area",
    352: "Vehicles slowing to look at accident(s) - Stationary traffic for 3 km",
    353: "Vehicles slowing to look at accident(s) - Queuing traffic for 3 km",
    354: "Vehicles slowing to look at accident(s) - Slow traffic for 3 km",
    355: "Vehicles slowing to look at accident(s) - Danger!",
    356: "Shed load(s) - Stationary traffic for 3 km",
    357: "Shed load(s) - Queuing traffic for 3 km",
    358: "Shed load(s) - Slow traffic for 3 km",
    359: "Shed load(s) - Danger!",
    360: "Overturned vehicle(s) - Stationary traffic",
    361: "Overturned vehicle(s) - Danger of stationary traffic!",
    362: "Overturned vehicle(s) - Queuing traffic",
    363: "Overturned vehicle(s) - Danger of queuing traffic!",
    364: "Overturned vehicle(s) - Slow traffic",
    365: "Overturned vehicle(s) - Slow traffic expected",
    366: "Overturned vehicle(s) - Heavy traffic",
    367: "Overturned vehicle(s) - Heavy traffic expected",
    368: "Overturned vehicle(s) - Traffic building up",
    369: "Blocked by overturned vehicle(s)",
    370: "Overturned vehicle(s) - Right lane blocked",
    371: "Overturned vehicle(s) - Centre lane blocked",
    372: "Overturned vehicle(s) - Left lane blocked",
    373: "Overturned vehicle(s) - Two lanes blocked",
    374: "Overturned vehicle(s) - Three lanes blocked",
    375: "Overturned vehicle - Delays",
    376: "Overturned vehicle - Delays expected",
    377: "Overturned vehicle - Long delays",
    378: "Overturned vehicle(s) - Danger!",
    379: "Stationary traffic due to earlier accident(s)",
    380: "Danger of stationary traffic due to earlier accident(s)!",
    381: "Queuing traffic due to earlier accident(s)",
    382: "Danger of queuing traffic due to earlier accident(s)!",
    383: "Slow traffic due to earlier accident(s)",
    385: "Heavy traffic due to earlier accident(s)",
    387: "Traffic building up due to earlier accident(s)",
    388: "Delays due to earlier accident",
    390: "Long delays due to earlier accident",
    391: "Accident investigation work - Danger!",
    392: "Secondary accident(s) - Danger!",
    393: "Broken down vehicle(s) - Danger!",
    394: "Broken down heavy lorr(y/ies) - Danger!",
    395: "Road cleared",
    396: "Incident cleared",
    397: "Rescue and recovery work in progress",
    399: "[Message cancelled]",
    401: "Closed road/highway",
    402: "Blocked road/highway",
    403: "Closed road/highway for heavy vehicles",
    404: "No through traffic for heavy lorries",
    405: "No through traffic",
    406: "Entry slip road closed",
    407: "Exit slip road closed",
    408: "Slip roads closed",
    409: "Slip road restrictions",
    410: "Closure ahead - Stationary traffic",
    411: "Closure ahead - Stationary traffic for 1 km",
    412: "Closure ahead - Stationary traffic for 2 km",
    413: "Closure ahead - Stationary traffic for 4 km",
    414: "Closure ahead - Stationary traffic for 6 km",
    415: "Closure ahead - Stationary traffic for 10 km",
    416: "Closure ahead - Danger of stationary traffic!",
    417: "Closure ahead - Queuing traffic",
    418: "Closure ahead - Queuing traffic for 1 km",
    419: "Closure ahead - Queuing traffic for 2 km",
    420: "Closure ahead - Queuing traffic for 4 km",
    421: "Closure ahead - Queuing traffic for 6 km",
    422: "Closure ahead - Queuing traffic for 10 km",
    423: "Closure ahead - Danger of queuing traffic!",
    424: "Closure ahead - Slow traffic",
    425: "Closure ahead - Slow traffic for 1 km",
    426: "Closure ahead - Slow traffic for 2 km",
    427: "Closure ahead - Slow traffic for 4 km",
    428: "Closure ahead - Slow traffic for 6 km",
    429: "Closure ahead - Slow traffic for 10 km",
    430: "Closure ahead - Slow traffic expected",
    431: "Closure ahead - Heavy traffic",
    432: "Closure ahead - Heavy traffic expected",
    433: "Closure ahead - Traffic flowing freely",
    434: "Closure ahead - Traffic building up",
    435: "Closure ahead - Delays",
    436: "Closure ahead - Delays expected",
    437: "Closure ahead - Long delays",
    438: "Blocked ahead - Stationary traffic",
    439: "Blocked ahead - Stationary traffic for 1 km",
    440: "Blocked ahead - Stationary traffic for 2 km",
    441: "Blocked ahead - Stationary traffic for 4 km",
    442: "Blocked ahead - Stationary traffic for 6 km",
    443: "Blocked ahead - Stationary traffic for 10 km",
    444: "Blocked ahead - Danger of stationary traffic!",
    445: "Blocked ahead - Queuing traffic",
    446: "Blocked ahead - Queuing traffic for 1 km",
    447: "Blocked ahead - Queuing traffic for 2 km",
    448: "Blocked ahead - Queuing traffic for 4 km",
    449: "Blocked ahead - Queuing traffic for 6 km",
    450: "Blocked ahead - Queuing traffic for 10 km",
    451: "Blocked ahead - Danger of queuing traffic!",
    452: "Blocked ahead - Slow traffic",
    453: "Blocked ahead - Slow traffic for 1 km",
    454: "Blocked ahead - Slow traffic for 2 km",
    455: "Blocked ahead - Slow traffic for 4 km",
    456: "Blocked ahead - Slow traffic for 6 km",
    457: "Blocked ahead - Slow traffic for 10 km",
    458: "Blocked ahead - Slow traffic expected",
    459: "Blocked ahead - Heavy traffic",
    460: "Blocked ahead - Heavy traffic expected",
    461: "Blocked ahead - Traffic flowing freely",
    462: "Blocked ahead - Traffic building up",
    463: "Blocked ahead - Delays",
    464: "Blocked ahead - Delays expected",
    465: "Blocked ahead - Long delays",
    466: "Slip roads reopened",
    467: "Reopened",
    468: "[Message cancelled]",
    469: "Closure ahead",
    470: "Blocked ahead",
    471: "Entry slip road(s) closed",
    472: "Entry slip road blocked",
    473: "Entry blocked",
    474: "Exit slip road(s) closed",
    475: "Exit slip road blocked",
    476: "Exit blocked",
    477: "Slip roads blocked",
    478: "Connecting carriageway closed",
    479: "Parallel carriageway closed",
    480: "Right-hand parallel carriageway closed",
    481: "Left-hand parallel carriageway closed",
    482: "Express lanes closed",
    483: "Through traffic lanes closed",
    484: "Local lanes closed",
    485: "Connecting carriageway blocked",
    486: "Parallel carriageway blocked",
    487: "Right-hand parallel carriageway blocked",
    488: "Left-hand parallel carriageway blocked",
    489: "Express lanes blocked",
    490: "Through traffic lanes blocked",
    491: "Local lanes blocked",
    492: "No motor vehicles",
    493: "Restrictions",
    494: "Road/highway closed for heavy lorries",
    495: "Closure ahead - Stationary traffic for 3 km",
    496: "Closure ahead - Queuing traffic for 3 km",
    497: "Closure ahead - Slow traffic for 3 km",
    498: "Blocked ahead - Stationary traffic for 3 km",
    499: "Blocked ahead - Queuing traffic for 3 km",
    500: "Lane(s) closed",
    501: "Right lane(s) closed",
    502: "Centre lane(s) closed",
    503: "Left lane(s) closed",
    504: "Hard shoulder closed",
    505: "Two lanes closed",
    506: "Three lanes closed",
    507: "Right lane(s) blocked",
    508: "Centre lane(s) blocked",
    509: "Left lane(s) blocked",
    510: "Hard shoulder blocked",
    511: "Two lanes blocked",
    512: "Three lanes blocked",
    513: "Single alternate line traffic",
    514: "Carriageway reduced to one lane",
    515: "Carriageway reduced to two lanes",
    516: "Carriageway reduced to three lanes",
    517: "Contraflow",
    518: "Narrow lanes",
    519: "Contraflow with narrow lanes",
    520: "Lane(s) blocked",
    521: "Lanes closed - Stationary traffic",
    522: "Lanes closed - Stationary traffic for 1 km",
    523: "Lanes closed - Stationary traffic for 2 km",
    524: "Lanes closed - Stationary traffic for 4 km",
    525: "Lanes closed - Stationary traffic for 6 km",
    526: "Lanes closed - Stationary traffic for 10 km",
    527: "Lanes closed - Danger of stationary traffic!",
    528: "Lanes closed - Queuing traffic",
    529: "Lanes closed - Queuing traffic for 1 km",
    530: "Lanes closed - Queuing traffic for 2 km",
    531: "Lanes closed - Queuing traffic for 4 km",
    532: "Lanes closed - Queuing traffic for 6 km",
    533: "Lanes closed - Queuing traffic for 10 km",
    534: "Lanes closed - Danger of queuing traffic!",
    535: "Lanes closed - Slow traffic",
    536: "Lanes closed - Slow traffic for 1 km",
    537: "Lanes closed - Slow traffic for 2 km",
    538: "Lanes closed - Slow traffic for 4 km",
    539: "Lanes closed - Slow traffic for 6 km",
    540: "Lanes closed - Slow traffic for 10 km",
    541: "Lanes closed - Slow traffic expected",
    542: "Lanes closed - Heavy traffic",
    543: "Lanes closed - Heavy traffic expected",
    544: "Lanes closed - Traffic flowing freely",
    545: "Lanes closed - Traffic building up",
    546: "Carriageway reduced to one lane - Stationary traffic",
    547: "Carriageway reduced to one lane - Danger of stationary traffic!",
    548: "Carriageway reduced to one lane - Queuing traffic",
    549: "Carriageway reduced to one lane - Danger of queuing traffic!",
    550: "Carriageway reduced to one lane - Slow traffic",
    551: "Carriageway reduced to one lane - Slow traffic expected",
    552: "Carriageway reduced to one lane - Heavy traffic",
    553: "Carriageway reduced to one lane - Heavy traffic expected",
    554: "Carriageway reduced to one lane - Traffic flowing freely",
    555: "Carriageway reduced to one lane - Traffic building up",
    556: "Carriageway reduced to two lanes - Stationary traffic",
    557: "Carriageway reduced to two lanes - Danger of stationary traffic!",
    558: "Carriageway reduced to two lanes - Queuing traffic",
    559: "Carriageway reduced to two lanes - Danger of queuing traffic!",
    560: "Carriageway reduced to two lanes - Slow traffic",
    561: "Carriageway reduced to two lanes - Slow traffic expected",
    562: "Carriageway reduced to two lanes - Heavy traffic",
    563: "Carriageway reduced to two lanes - Heavy traffic expected",
    564: "Carriageway reduced to two lanes - Traffic flowing freely",
    565: "Carriageway reduced to two lanes - Traffic building up",
    566: "Carriageway reduced to three lanes - Stationary traffic",
    567: "Carriageway reduced to three lanes - Danger of stationary traffic!",
    568: "Carriageway reduced to three lanes - Queuing traffic",
    569: "Carriageway reduced to three lanes - Danger of queuing traffic!",
    570: "Carriageway reduced to three lanes - Slow traffic",
    571: "Carriageway reduced to three lanes - Slow traffic expected",
    572: "Carriageway reduced to three lanes - Heavy traffic",
    573: "Carriageway reduced to three lanes - Heavy traffic expected",
    574: "Carriageway reduced to three lanes - Traffic flowing freely",
    575: "Carriageway reduced to three lanes - Traffic building up",
    576: "Contraflow - Stationary traffic",
    577: "Contraflow - Stationary traffic for 1 km",
    578: "Contraflow - Stationary traffic for 2 km",
    579: "Contraflow - Stationary traffic for 4 km",
    580: "Contraflow - Stationary traffic for 6 km",
    581: "Contraflow - Stationary traffic for 10 km",
    582: "Contraflow - Danger of stationary traffic!",
    583: "Contraflow - Queuing traffic",
    584: "Contraflow - Queuing traffic for 1 km",
    585: "Contraflow - Queuing traffic for 2 km",
    586: "Contraflow - Queuing traffic for 4 km",
    587: "Contraflow - Queuing traffic for 6 km",
    588: "Contraflow - Queuing traffic for 10 km",
    589: "Contraflow - Danger of queuing traffic!",
    590: "Contraflow - Slow traffic",
    591: "Contraflow - Slow traffic for 1 km",
    592: "Contraflow - Slow traffic for 2 km",
    593: "Contraflow - Slow traffic for 4 km",
    594: "Contraflow - Slow traffic for 6 km",
    595: "Contraflow - Slow traffic for 10 km",
    596: "Contraflow - Slow traffic expected",
    597: "Contraflow - Heavy traffic",
    598: "Contraflow - Heavy traffic expected",
    599: "Contraflow - Traffic flowing freely",
    600: "Contraflow - Traffic building up",
    601: "Contraflow - Carriageway reduced to one lane",
    602: "Contraflow - Carriageway reduced to two lanes",
    603: "Contraflow - Carriageway reduced to three lanes",
    604: "Narrow lanes - Stationary traffic",
    605: "Narrow lanes - Danger of stationary traffic!",
    606: "Narrow lanes - Queuing traffic",
    607: "Narrow lanes - Danger of queuing traffic!",
    608: "Narrow lanes - Slow traffic",
    609: "Narrow lanes - Slow traffic expected",
    610: "Narrow lanes - Heavy traffic",
    611: "Narrow lanes - Heavy traffic expected",
    612: "Narrow lanes - Traffic flowing freely",
    613: "Narrow lanes - Traffic building up",
    614: "Contraflow with narrow lanes - Stationary traffic",
    615: "Contraflow with narrow lanes - Danger of stationary traffic!",
    616: "Contraflow with narrow lanes - Queuing traffic",
    617: "Contraflow with narrow lanes - Danger of queuing traffic!",
    618: "Contraflow with narrow lanes - Slow traffic",
    619: "Contraflow with narrow lanes - Slow traffic expected",
    620: "Contraflow with narrow lanes - Heavy traffic",
    621: "Contraflow with narrow lanes - Heavy traffic expected",
    622: "Contraflow with narrow lanes - Traffic flowing freely",
    623: "Contraflow with narrow lanes - Traffic building up",
    624: "Lane closures removed",
    625: "[Message cancelled]",
    626: "Blocked ahead - Slow traffic for 3 km",
    627: "No motor vehicles without catalytic converters",
    628: "No motor vehicles with even-numbered registration plates",
    629: "No motor vehicles with odd-numbered registration plates",
    630: "Open",
    631: "Road cleared",
    632: "Entry reopened",
    633: "Exit reopened",
    634: "All carriageways reopened",
    635: "Motor vehicle restrictions lifted",
    636: "Traffic restrictions lifted",
    637: "Emergency lane closed",
    638: "Turning lane closed",
    639: "Crawler lane closed",
    640: "Slow vehicle lane closed",
    641: "One lane closed",
    642: "Emergency lane blocked",
    643: "Turning lane blocked",
    644: "Crawler lane blocked",
    645: "Slow vehicle lane blocked",
    646: "One lane blocked",
    647: "Carpool lane in operation",
    648: "Carpool lane closed",
    649: "Carpool lane blocked",
    650: "Carpool restrictions changed",
    651: "Lanes closed - Stationary traffic for 3 km",
    652: "Lanes closed - Queuing traffic for 3 km",
    653: "Lanes closed - Slow traffic for 3 km",
    654: "Contraflow - Stationary traffic for 3 km",
    655: "Contraflow - Queuing traffic for 3 km",
    656: "Contraflow - Slow traffic for 3 km",
    657: "Lane blockages cleared",
    658: "Contraflow removed",
    659: "Carpool restrictions lifted",
    660: "Lane restrictions lifted",
    661: "Use of hard shoulder allowed",
    662: "Normal lane regulations restored",
    663: "All carriageways cleared",
    664: "Carriageway closed",
    665: "Both directions closed",
    666: "Intermittent short term closures",
    671: "Bus lane available for carpools",
    672: "[Message cancelled]",
    673: "[Message cancelled]",
    675: "Salting vehicles",
    676: "Bus lane blocked",
    678: "Heavy vehicle lane closed",
    679: "Heavy vehicle lane blocked",
    680: "Reopened for through traffic",
    681: "Snowploughs",
    701: "Roadworks",
    702: "Major roadworks",
    703: "Maintenance work",
    704: "Resurfacing work",
    705: "Central reservation work",
    706: "Road marking work",
    707: "Bridge maintenance work",
    708: "Temporary traffic lights",
    709: "Blasting work",
    710: "Roadworks - Stationary traffic",
    711: "Roadworks - Stationary traffic for 1 km",
    712: "Roadworks - Stationary traffic for 2 km",
    713: "Roadworks - Stationary traffic for 4 km",
    714: "Roadworks - Stationary traffic for 6 km",
    715: "Roadworks - Stationary traffic for 10 km",
    716: "Roadworks - Danger of stationary traffic!",
    717: "Roadworks - Queuing traffic",
    718: "Roadworks - Queuing traffic for 1 km",
    719: "Roadworks - Queuing traffic for 2 km",
    720: "Roadworks - Queuing traffic for 4 km",
    721: "Roadworks - Queuing traffic for 6 km",
    722: "Roadworks - Queuing traffic for 10 km",
    723: "Roadworks - Danger of queuing traffic!",
    724: "Roadworks - Slow traffic",
    725: "Roadworks - Slow traffic for 1 km",
    726: "Roadworks - Slow traffic for 2 km",
    727: "Roadworks - Slow traffic for 4 km",
    728: "Roadworks - Slow traffic for 6 km",
    729: "Roadworks - Slow traffic for 10 km",
    730: "Roadworks - Slow traffic expected",
    731: "Roadworks - Heavy traffic",
    732: "Roadworks - Heavy traffic expected",
    733: "Roadworks - Traffic flowing freely",
    734: "Roadworks - Traffic building up",
    735: "Road/highway closed due to roadworks",
    736: "Roadworks - Right lane closed",
    737: "Roadworks - Centre lane closed",
    738: "Roadworks - Left lane closed",
    739: "Roadworks - Hard shoulder closed",
    740: "Roadworks - Two lanes closed",
    741: "Roadworks - Three lanes closed",
    742: "Roadworks - Single alternate line traffic",
    743: "Roadworks - Carriageway reduced to one lane",
    744: "Roadworks - Carriageway reduced to two lanes",
    745: "Roadworks - Carriageway reduced to three lanes",
    746: "Roadworks - Contraflow",
    747: "Roadworks - Delays",
    748: "Roadworks - Delays expected",
    749: "Roadworks - Long delays",
    750: "Resurfacing work - Stationary traffic",
    751: "Resurfacing work - Stationary traffic for 1 km",
    752: "Resurfacing work - Stationary traffic for 2 km",
    753: "Resurfacing work - Stationary traffic for 4 km",
    754: "Resurfacing work - Stationary traffic for 6 km",
    755: "Resurfacing work - Stationary traffic for 10 km",
    756: "Resurfacing work - Danger of stationary traffic!",
    757: "Resurfacing work - Queuing traffic",
    758: "Resurfacing work - Queuing traffic for 1 km",
    759: "Resurfacing work - Queuing traffic for 2 km",
    760: "Resurfacing work - Queuing traffic for 4 km",
    761: "Resurfacing work - Queuing traffic for 6 km",
    762: "Resurfacing work - Queuing traffic for 10 km",
    763: "Resurfacing work - Danger of queuing traffic!",
    764: "Resurfacing work - Slow traffic",
    765: "Resurfacing work - Slow traffic for 1 km",
    766: "Resurfacing work - Slow traffic for 2 km",
    767: "Resurfacing work - Slow traffic for 4 km",
    768: "Resurfacing work - Slow traffic for 6 km",
    769: "Resurfacing work - Slow traffic for 10 km",
    770: "Resurfacing work - Slow traffic expected",
    771: "Resurfacing work - Heavy traffic",
    772: "Resurfacing work - Heavy traffic expected",
    773: "Resurfacing work - Traffic flowing freely",
    774: "Resurfacing work - Traffic building up",
    775: "Resurfacing work - Single alternate line traffic",
    776: "Resurfacing work - Carriageway reduced to one lane",
    777: "Resurfacing work - Carriageway reduced to two lanes",
    778: "Resurfacing work - Carriageway reduced to three lanes",
    779: "Resurfacing work - Contraflow",
    780: "Resurfacing work - Delays",
    781: "Resurfacing work - Delays expected",
    782: "Resurfacing work - Long delays",
    783: "Road marking work - Stationary traffic",
    784: "Road marking work - Danger of stationary traffic!",
    785: "Road marking work - Queuing traffic",
    786: "Road marking work - Danger of queuing traffic!",
    787: "Road marking work - Slow traffic",
    788: "Road marking work - Slow traffic expected",
    789: "Road marking work - Heavy traffic",
    790: "Road marking work - Heavy traffic expected",
    791: "Road marking work - Traffic flowing freely",
    792: "Road marking work - Traffic building up",
    793: "Road marking work - Right lane closed",
    794: "Road marking work - Centre lane closed",
    795: "Road marking work - Left lane closed",
    796: "Road marking work - Hard shoulder closed",
    797: "Road marking work - Two lanes closed",
    798: "Road marking work - Three lanes closed",
    799: "Road/highway closed for bridge demolition work",
    800: "Roadworks cleared",
    801: "[Message cancelled]",
    802: "Long-term roadworks",
    803: "Construction work",
    804: "Slow moving maintenance vehicles",
    805: "Bridge demolition work",
    806: "Water main work",
    807: "Gas main work",
    808: "Work on buried cables",
    809: "Work on buried services",
    810: "New roadworks layout",
    811: "New road layout",
    812: "Roadworks - Stationary traffic for 3 km",
    813: "Roadworks - Queuing traffic for 3 km",
    814: "Roadworks - Slow traffic for 3 km",
    815: "Roadworks during the day time",
    816: "Roadworks during off-peak periods",
    817: "Roadworks during the night",
    818: "Resurfacing work - Stationary traffic for 3 km",
    819: "Resurfacing work - Queuing traffic for 3 km",
    820: "Resurfacing work - Slow traffic for 3 km",
    821: "Resurfacing work during the day time",
    822: "Resurfacing work during off-peak periods",
    823: "Resurfacing work during the night",
    824: "Road marking work - Danger!",
    825: "Slow moving maintenance vehicles - Stationary traffic",
    826: "Slow moving maintenance vehicles - Danger of stationary traffic!",
    827: "Slow moving maintenance vehicles - Queuing traffic",
    828: "Slow moving maintenance vehicles - Danger of queuing traffic!",
    829: "Slow moving maintenance vehicles - Slow traffic",
    830: "Slow moving maintenance vehicles - Slow traffic expected",
    831: "Slow moving maintenance vehicles - Heavy traffic",
    832: "Slow moving maintenance vehicles - Heavy traffic expected",
    833: "Slow moving maintenance vehicles - Traffic flowing freely",
    834: "Slow moving maintenance vehicles - Traffic building up",
    835: "Slow moving maintenance vehicles - Right lane closed",
    836: "Slow moving maintenance vehicles - Centre lane closed",
    837: "Slow moving maintenance vehicles - Left lane closed",
    838: "Slow moving maintenance vehicles - Two lanes closed",
    839: "Slow moving maintenance vehicles - Three lanes closed",
    840: "Water main work - Delays",
    841: "Water main work - Delays expected",
    842: "Water main work - Long delays",
    843: "Gas main work - Delays",
    844: "Gas main work - Delays expected",
    845: "Gas main work - Long delays",
    846: "Work on buried cables - Delays",
    847: "Work on buried cables - Delays expected",
    848: "Work on buried cables - Long delays",
    849: "Work on buried services - Delays",
    850: "Work on buried services - Delays expected",
    851: "Work on buried services - Long delays",
    852: "Construction traffic merging",
    853: "Roadwork clearance in progress",
    854: "Maintenance work cleared",
    855: "Road layout unchanged",
    856: "Construction traffic merging - Danger!",
    857: "Unprotected accident area(s)",
    858: "Danger of unprotected accident area(s)!",
    859: "Unlit vehicle(s) on the road",
    860: "Danger of unlit vehicle(s) on the road!",
    861: "Snow and ice debris",
    862: "Danger of snow and ice debris!",
    897: "People throwing objects onto the road - Danger!",
    898: "Obstruction warning withdrawn",
    899: "Clearance work in progress - road is free again",
    900: "Flooding expected",
    901: "Obstruction(s) on roadway",
    902: "Obstructions on the road - Danger!",
    903: "Spillage on the road",
    904: "Storm damage",
    905: "Fallen trees",
    906: "Fallen trees - Danger!",
    907: "Flooding",
    908: "Flooding - Danger!",
    909: "Flash floods",
    910: "Danger of flash floods!",
    911: "Avalanches",
    912: "Avalanche risk",
    913: "Rockfalls",
    914: "Landslips",
    915: "Earthquake damage",
    916: "Road surface in poor condition",
    917: "Subsidence",
    918: "Collapsed sewer(s)",
    919: "Burst water main",
    920: "Gas leak",
    921: "Serious fire",
    922: "Animals on roadway",
    923: "Animals on the road - Danger!",
    924: "Clearance work",
    925: "Blocked by storm damage",
    926: "Blocked by fallen trees",
    927: "Fallen tree(s) - Passable with care",
    928: "Flooding - Stationary traffic",
    929: "Flooding - Danger of stationary traffic!",
    930: "Flooding - Queuing traffic",
    931: "Flooding - Danger of queuing traffic!",
    932: "Flooding - Slow traffic",
    933: "Flooding - Slow traffic expected",
    934: "Flooding - Heavy traffic",
    935: "Flooding - Heavy traffic expected",
    936: "Flooding - Traffic flowing freely",
    937: "Flooding - Traffic building up",
    938: "Road/highway closed due to flooding",
    939: "Flooding - Delays",
    940: "Flooding - Delays expected",
    941: "Flooding - Long delays",
    942: "Flooding - Passable with care",
    943: "Road/highway closed due to avalanches",
    944: "Avalanches - Passable with care",
    945: "Road/highway closed due to rockfalls",
    946: "Rockfalls - Passable with care",
    947: "Road/highway closed due to landslips",
    948: "Landslips - Passable with care",
    949: "Road/highywa closed due to subsidence",
    950: "Subsidence - Single alternate line traffic",
    951: "Subsidence - Carriageway reduced to one lane",
    952: "Subsidence - Carriageway reduced to two lanes",
    953: "Subsidence - Carriageway reduced to three lanes",
    954: "Subsidence - Contraflow in operation",
    955: "Subsidence - Passable with care",
    956: "Road/highway closed due to sewer collapse",
    957: "Road/highway closed due to burst water main",
    958: "Burst water main - Delays",
    959: "Burst water main - Delays expected",
    960: "Burst water main - Long delays",
    961: "Road closed due to gas leak",
    962: "Gas leak - Delays",
    963: "Gas leak - Delays expected",
    964: "Gas leak - Long delays",
    965: "Road closed due to serious fire",
    966: "Serious fire - Delays",
    967: "Serious fire - Delays expected",
    968: "Serious fire - Long delays",
    969: "Road closed for clearance work",
    970: "Road free again",
    971: "[Message cancelled]",
    972: "Storm damage expected",
    973: "Fallen power cables",
    974: "Sewer overflow",
    975: "Ice build-up",
    976: "Mud slide",
    977: "Grass fire",
    978: "Air crash",
    979: "Rail crash",
    980: "Blocked by obstruction(s) on the road",
    981: "Obstructions on the road - Passable with care",
    982: "Blocked due to spillage on roadway",
    983: "Spillage on the road - Passable with care",
    984: "Spillage on the road - Danger!",
    985: "Storm damage - Passable with care",
    986: "Storm damage - Danger!",
    987: "Blocked by fallen power cables",
    988: "Fallen power cables - Passable with care",
    989: "Fallen power cables - Danger!",
    990: "Sewer overflow - Danger!",
    991: "Flash floods - Danger!",
    992: "Avalanches - Danger!",
    993: "Road closed due to avalanche risk",
    994: "Avalanche risk - Danger!",
    995: "Road/highway closed due to ice build-up",
    996: "Ice build-up - Passable with care",
    997: "Ice build-up - Single alternate traffic",
    998: "Rockfalls - Danger!",
    999: "Landslips -Danger!",
    1000: "Earthquake damage -Danger!",
    1001: "Hazardous driving conditions",
    1002: "Danger of aquaplaning!",
    1003: "Slippery road",
    1004: "Mud on road",
    1005: "Leaves on road",
    1006: "Ice",
    1007: "Danger of ice!",
    1008: "Black ice",
    1009: "Freezing rain",
    1010: "Wet and icy roads",
    1011: "Slush",
    1012: "Snow on the road",
    1013: "Packed snow",
    1014: "Fresh snow",
    1015: "Deep snow",
    1016: "Snow drifts",
    1017: "Slippery due to spillage on roadway",
    1018: "Slippery road due to snow",
    1019: "Slippery road due to frost",
    1020: "Road blocked by snow",
    1021: "Snow on the road - Carriageway reduced to one lane",
    1022: "Snow on the road - Carriageway reduced to two lanes",
    1023: "Snow on the road - Carriageway reduced to three lanes",
    1024: "Conditions of road surface improved",
    1025: "[Message cancelled]",
    1026: "Subsidence - Danger!",
    1027: "Sewer collapse - Delays",
    1028: "Sewer collapse - Delays expected",
    1029: "Sewer collapse - Long delays",
    1030: "Sewer collapse - Danger!",
    1031: "Burst water main - Danger!",
    1032: "Gas leak - Danger!",
    1033: "Serious fire - Danger!",
    1034: "Clearance work - Danger!",
    1035: "Impassable",
    1036: "Almost impassable",
    1037: "Extremely hazardous driving conditions",
    1038: "Difficult driving conditions",
    1039: "Passable with care",
    1040: "Passable",
    1041: "Surface water hazard",
    1042: "Loose sand on road",
    1043: "Loose chippings",
    1044: "Oil on road",
    1045: "Petrol on road",
    1046: "Ice expected",
    1047: "Icy patches",
    1048: "Danger of icy patches!",
    1049: "Icy patches expected",
    1050: "Danger of black ice!",
    1051: "Black ice expected",
    1052: "Freezing rain expected",
    1053: "Snow drifts expected",
    1054: "Slippery due to loose sand on roadway",
    1055: "Mud on road - Danger!",
    1056: "Loose chippings - Danger!",
    1057: "Oil on road - Danger!",
    1058: "Petrol on road - Danger!",
    1059: "Road surface in poor condition - Danger!",
    1060: "Icy patches on bridges",
    1061: "Danger of icy patches on bridges!",
    1062: "Icy patches on bridges - in shaded areas and on slip roads",
    1063: "Impassable for heavy vehicles",
    1064: "Impassable for vehicles with trailers",
    1065: "Driving conditions improved",
    1066: "Rescue and recovery work in progress - Danger!",
    1067: "Large animals on roadway",
    1068: "Herds of animals on roadway",
    1069: "Skid hazard reduced",
    1070: "Snow cleared",
    1071: "Road conditions forecast withdrawn",
    1072: "[Message cancelled]",
    1073: "Extremely hazardous driving conditions expected",
    1074: "Freezing rain expected",
    1075: "Danger of road being blocked by snow!",
    1079: "Temperature falling rapidly",
    1080: "Extreme heat",
    1081: "Extreme cold",
    1082: "Less extreme temperatures",
    1083: "Current temperature",
    1084: "House fire",
    1085: "Forest fire",
    1086: "Vehicle stuck under bridge",
    1090: "Volcano eruption warning",
    1101: "Heavy snowfall",
    1102: "Heavy snowfall - Visibility reduced to less than 30 m",
    1103: "Heavy snowfall - Visibility reduced to less than 50 m",
    1104: "Snowfall",
    1105: "Snowfall - Visibility reduced to less than 100 m",
    1106: "Hail",
    1107: "Sleet",
    1108: "Thunderstorms",
    1109: "Heavy rain",
    1110: "Heavy rain - Visibility reduced to less than 30 m",
    1111: "Heavy rain - Visibility reduced to less than 50 m",
    1112: "Rain",
    1113: "Rain - Visibility reduced to less than 100 m",
    1114: "Showers",
    1115: "Heavy frost",
    1116: "Frost",
    1117: "Overcast weather [+ Weather data transmission]",
    1118: "Mostly cloudy",
    1119: "Partly cloudy",
    1120: "Sunny periods",
    1121: "Clear weather",
    1122: "Sunny weather",
    1123: "Mostly dry weather",
    1124: "Dry weather",
    1125: "Sunny periods and with showers",
    1126: "Weather situation improved",
    1127: "[Message cancelled]",
    1128: "Winter storm",
    1129: "Winter storm",
    1130: "Blizzard",
    1131: "Blizzard",
    1132: "Damaging hail",
    1133: "Damaging hail",
    1134: "Heavy snowfall - Visibility reduced",
    1135: "Snowfall - Visibility reduced",
    1136: "Heavy rain - Visibility reduced",
    1137: "Rain - Visibility reduced",
    1138: "Severe weather warnings cancelled",
    1139: "[Message cancelled]",
    1140: "Weather forecast withdrawn",
    1141: "Fog forecast withdrawn",
    1143: "Slippery road expected",
    1151: "Heavy snowfall",
    1152: "Snowfall",
    1153: "Hail",
    1154: "Sleet",
    1155: "Thunderstorms",
    1156: "Heavy rain",
    1157: "Rain",
    1158: "Showers",
    1159: "Heavy frost",
    1160: "Frost",
    1165: "Rain changing to snow",
    1166: "Snow changing to rain",
    1170: "Heavy snowfall expected",
    1171: "Heavy rain expected",
    1172: "Weather expected to improve",
    1173: "Blizzard expected",
    1174: "Damaging hail expected",
    1175: "Reduced visibility expected",
    1176: "Freezing fog expected - Danger of slippery roads!",
    1177: "Dense fog expected",
    1178: "Patchy fog expected",
    1179: "Visibility expected to improve",
    1180: "Adverse weather warning withdrawn",
    1190: "Severe smog",
    1191: "Severe exhaust pollution",
    1201: "Tornadoes",
    1202: "Hurricane force winds",
    1203: "Gales",
    1204: "Storm force winds",
    1205: "Strong winds",
    1206: "Moderate winds",
    1207: "Light winds",
    1208: "Calm weather",
    1209: "Gusty winds",
    1210: "Crosswinds",
    1211: "Strong winds affecting high-sided vehicles",
    1212: "Road/highway closed for high-sided vehicles due to strong winds",
    1213: "Strong winds easing",
    1214: "[Message cancelled]",
    1215: "Restrictions for high-sided vehicles lifted",
    1216: "Tornado watch cancelled",
    1217: "Tornado warning ended",
    1218: "Wind forecast withdrawn",
    1219: "[Message cancelled]",
    1251: "Tornadoes",
    1252: "Hurricane force winds",
    1253: "Gales",
    1254: "Storm force winds",
    1255: "Strong winds",
    1256: "Strong wind forecast withdrawn",
    1300: "Snowfall and fog expected",
    1301: "Dense fog",
    1302: "Dense fog - Visibility reduced to less than 30 m",
    1303: "Dense fog - Visibility reduced to less than 50 m",
    1304: "Fog",
    1305: "Fog - Visibility reduced to less than 100 m",
    1306: "Fog",
    1307: "Patchy fog",
    1308: "Freezing fog",
    1309: "Smoke hazard",
    1310: "Blowing dust",
    1311: "Severe exhaust pollution",
    1312: "Snowfall and fog",
    1313: "Visibility improved",
    1314: "[Message cancelled]",
    1315: "Dense fog",
    1316: "Patchy fog",
    1317: "Freezing fog",
    1318: "Visibility reduced",
    1319: "Visibility reduced to less than 30 m",
    1320: "Visibility reduced to less than 50 m",
    1321: "Visibility reduced to less than 100 m",
    1322: "White out",
    1323: "Blowing snow",
    1324: "Spray hazard",
    1325: "Low sun glare",
    1326: "Sandstorms",
    1327: "Sandstorms",
    1328: "Air quality - good",
    1329: "Air quality - fair",
    1330: "Air quality - poor",
    1331: "Air quality - very poor",
    1332: "Smog alert",
    1333: "Smog",
    1334: "Pollen count - high",
    1335: "Pollen count - medium",
    1336: "Pollen count - low",
    1337: "Freezing fog - Slippery roads",
    1338: "No motor vehicles due to smog alert",
    1339: "Air quality improved",
    1340: "Swarms of insects",
    1345: "Fog clearing",
    1346: "Fog forecast withdrawn",
    1351: "Maximum temperature",
    1352: "Hot [Maximal temperature mentioned]",
    1353: "Warm [Maximal temperature mentioned]",
    1354: "Mild [Maximal temperature mentioned]",
    1355: "Cool [Maximal temperature mentioned]",
    1356: "Cold [Maximal temperature mentioned]",
    1357: "Very cold [Maximal temperature mentioned]",
    1358: "[Message cancelled]",
    1359: "Temperature rising [Temperature mentioned]",
    1360: "Temperature falling rapidly [Temperature mentioned]",
    1361: "Temperature indication [Temperature mentioned]",
    1362: "Effective temperature [Temperature value mentioned] - with wind chill",
    1364: "Extreme heat [Temperature mentioned]",
    1365: "Extreme cold [Temperature mentioned]",
    1401: "Minimum temperature [Temperature value mentioned]",
    1402: "Very warm [Minimum temperature mentioned]",
    1403: "Warm [Minimum temperature mentioned]",
    1404: "Mild [Minimum temperature mentioned]",
    1405: "Cool [Minimum temperature mentioned]",
    1406: "Cold [Minimum temperature mentioned]",
    1407: "Very cold [Minimum temperature mentioned]",
    1408: "Less extreme temperatures expected",
    1449: "Emergency training in progress",
    1450: "International sports meeting",
    1451: "Match",
    1452: "Tournament",
    1453: "Athletics meeting",
    1454: "Ball game",
    1455: "Boxing tournament",
    1456: "Bull fight",
    1457: "Cricket match",
    1458: "Cycle race",
    1459: "Football match",
    1460: "Golf tournament",
    1461: "Marathon",
    1462: "Race meeting",
    1463: "Rugby match",
    1464: "Show jumping",
    1465: "Tennis tournament",
    1466: "Water sports meeting",
    1467: "Winter sports meeting",
    1468: "Funfair",
    1469: "Trade fair",
    1470: "Procession",
    1471: "Sightseers obstructing access",
    1472: "People on roadway",
    1473: "Children on roadway",
    1474: "Cyclists on roadway",
    1475: "Strike",
    1476: "Security incident",
    1477: "Police checkpoint",
    1478: "Terrorist incident",
    1479: "Gunfire on roadway - Danger!",
    1480: "Civil emergency",
    1481: "Air raid - Danger!",
    1482: "People on roadway - Danger!",
    1483: "Children on roadway - Danger!",
    1484: "Cyclists on roadway - Danger!",
    1485: "Road/highway closed due to security incident",
    1486: "Security incident - Delays",
    1487: "Security incident - Delays expected",
    1488: "Security incident - Long delays",
    1489: "Police checkpoint - Delays",
    1490: "Police checkpoint - Delays expected",
    1491: "Police checkpoint - Long delays",
    1492: "Security alert withdrawn",
    1493: "Sports traffic cleared",
    1494: "Evacuation",
    1495: "Evacuation - Heavy traffic",
    1496: "Traffic disruption cleared",
    1497: "Military training in progress",
    1498: "Police activity ongoing",
    1499: "Medical emergency ongoing",
    1500: "Child abduction in progress",
    1501: "Major event",
    1502: "Sports event meeting",
    1503: "Show",
    1504: "Festival",
    1505: "Exhibition",
    1506: "Fair",
    1507: "Market",
    1508: "Ceremonial event",
    1509: "State occasion",
    1510: "Parade",
    1511: "Crowd",
    1512: "March",
    1513: "Demonstration",
    1514: "Public disturbance",
    1515: "Security alert",
    1516: "Bomb alert",
    1517: "Major event - Stationary traffic",
    1518: "Major event - Danger of stationary traffic!",
    1519: "Major event - Queuing traffic",
    1520: "Major event - Danger of queuing traffic!",
    1521: "Major event - Slow traffic",
    1522: "Major event - Slow traffic expected",
    1523: "Major event - Heavy traffic",
    1524: "Major event - Heavy traffic expected",
    1525: "Major event - Traffic flowing freely",
    1526: "Major event - Traffic building up",
    1527: "Road/highway closed due to major event",
    1528: "Major event - Delays",
    1529: "Major event - Delays expected",
    1530: "Major event - Long delays",
    1531: "Sports meeting - Stationary traffic",
    1532: "Sports meeting - Danger of stationary traffic!",
    1533: "Sports meeting - Queuing traffic",
    1534: "Sports meeting - Danger of queuing traffic!",
    1535: "Sports meeting - Slow traffic",
    1536: "Sports meeting - Slow traffic expected",
    1537: "Sports meeting - Heavy traffic",
    1538: "Sports meeting - Heavy traffic expected",
    1539: "Sports meeting - Traffic flowing freely",
    1540: "Sports meeting - Traffic building up",
    1541: "Road closed due to sports meeting",
    1542: "Sports meeting - Delays",
    1543: "Sports meeting - Delays expected",
    1544: "Sports meeting - Long delays",
    1545: "Fair - Stationary traffic",
    1546: "Fair - Danger of stationary traffic!",
    1547: "Fair - Queuing traffic",
    1548: "Fair - Danger of queuing traffic!",
    1549: "Fair - Slow traffic",
    1550: "Fair - Slow traffic expected",
    1551: "Fair - Heavy traffic",
    1552: "Fair - Heavy traffic expected",
    1553: "Fair - Traffic flowing freely",
    1554: "Fair - Traffic building up",
    1555: "Road closed due to fair",
    1556: "Fair - Delays",
    1557: "Fair - Delays expected",
    1558: "Fair - Long delays",
    1559: "Road closed due to parade",
    1560: "Parade - Delays",
    1561: "Parade - Delays expected",
    1562: "Parade - Long delays",
    1563: "Road closed due to strike",
    1564: "Strike - Delays",
    1565: "Strike - Delays expected",
    1566: "Strike - Long delays",
    1567: "Road closed due to demonstration",
    1568: "Demonstration - Delays",
    1569: "Demonstration - Delays expected",
    1570: "Demonstration - Long delays",
    1571: "Security alert - Stationary traffic",
    1572: "Security alert - Danger of stationary traffic!",
    1573: "Security alert - Queuing traffic",
    1574: "Security alert - Danger of queuing traffic!",
    1575: "Security alert - Slow traffic",
    1576: "Security alert - Slow traffic expected",
    1577: "Security alert - Heavy traffic",
    1578: "Security alert - Heavy traffic expected",
    1579: "Security alert - Traffic building up",
    1580: "Road closed due to security alert",
    1581: "Security alert - Delays",
    1582: "Security alert - Delays expected",
    1583: "Security alert - Long delays",
    1584: "Traffic has returned to normal",
    1585: "[Message cancelled]",
    1586: "Security alert - Traffic flowing freely",
    1587: "Air raid warning cancelled",
    1588: "Civil emergency cancelled",
    1589: "[Message cancelled]",
    1590: "Several major events",
    1591: "Information about major event no longer valid",
    1592: "Automobile race",
    1593: "Baseball game",
    1594: "Basketball game",
    1595: "Boat race",
    1596: "Concert",
    1597: "Hockey game",
    1601: "Delays",
    1602: "Delays up to 15 minutes",
    1603: "Delays up to 30 minutes",
    1604: "Delays up to one hour",
    1605: "Delays up to two hours",
    1606: "Delays of several hours",
    1607: "Delays expected",
    1608: "Long delays",
    1609: "Delays for heavy vehicles",
    1610: "Delays up to 15 minutes for heavy lorr(y/ies)",
    1611: "Delays up to 30 minutes for heavy lorr(y/ies)",
    1612: "Delays up to one hour for heavy lorr(y/ies)",
    1613: "Delays up to two hours for heavy lorr(y/ies)",
    1614: "Delays of several hours for heavy lorr(y/ies)",
    1615: "Service suspended",
    1616: "Service withdrawn",
    1617: "Service(s) fully booked",
    1618: "Service(s) fully booked for heavy vehicles",
    1619: "Normal services resumed",
    1620: "[Message cancelled]",
    1621: "Delays up to 5 minutes",
    1622: "Delays up to 10 minutes",
    1623: "Delays up to 20 minutes",
    1624: "Delays up to 25 minutes",
    1625: "Delays up to 40 minutes",
    1626: "Delays up to 50 minutes",
    1627: "Delays up to 90 minutes",
    1628: "Delays up to three hours",
    1629: "Delays up to four hours",
    1630: "Delays up to five hours",
    1631: "Very long delays",
    1632: "Delays of uncertain duration",
    1633: "Delayed until further notice",
    1634: "Cancellations",
    1635: "Park and ride service not operating",
    1636: "Special public transport services operating",
    1637: "Normal services not operating",
    1638: "Rail services not operating",
    1639: "Bus services not operating",
    1640: "Shuttle service operating",
    1641: "Free shuttle service operating",
    1642: "Delays for heavy lorr(y/ies)",
    1643: "Delays for buses",
    1644: "Service(s) fully booked for heavy lorr(y/ies)",
    1645: "Service(s) fully booked for buses",
    1646: "Next departure for heavy lorr(y/ies)",
    1647: "Next departure for buses",
    1648: "Delays cleared",
    1649: "Rapid transit service not operating",
    1650: "Delays possible",
    1651: "Underground service not operating",
    1652: "Cancellations expected",
    1653: "Long delays expected",
    1654: "Very long delays expected",
    1655: "All services fully booked",
    1656: "Next arrival",
    1657: "Rail services irregular - Delays",
    1658: "Bus services irregular - Delays",
    1659: "Underground services irregular",
    1660: "Normal public transport services resumed",
    1661: "Ferry service not operating",
    1662: "Park and ride trip time",
    1663: "Delay expected to be cleared",
    1664: "Demonstration by vehicles",
    1680: "Delays have to be expected",
    1681: "Delays of several hours have to be expected",
    1682: "Closure ahead - Delays have to be expected",
    1683: "Roadworks - Delays have to be expected",
    1684: "Flooding - Delays have to be expected",
    1685: "Major event - Delays have to be expected",
    1686: "Strike - Delays have to be expected",
    1687: "Delays of several hours for heavy lorries have to be expected",
    1688: "Long delays have to be expected",
    1689: "Very long delays have to be expected",
    1690: "Delay forecast withdrawn",
    1691: "[Message cancelled]",
    1695: "Current trip time",
    1696: "Expected trip time",
    1700: "Slow moving maintenance vehicle(s)",
    1701: "Vehicle(s) on wrong carriageway",
    1702: "Dangerous vehicle warning cleared",
    1703: "[Message cancelled]",
    1704: "Reckless driver(s)",
    1705: "Prohibited vehicle(s) on the roadway",
    1706: "Emergency vehicles",
    1707: "High-speed emergency vehicles",
    1708: "High-speed chase",
    1709: "Spillage occurring from moving vehicle",
    1710: "Objects falling from moving vehicle",
    1711: "Emergency vehicle warning cleared",
    1712: "Road cleared",
    1720: "Rail services irregular",
    1721: "Public transport services not operating",
    1731: "Abnormal load(s) - Danger!",
    1732: "Wide load(s) - Danger!",
    1733: "Long load(s) - Danger!",
    1734: "Slow vehicle(s) - Danger!",
    1735: "Track-laying vehicle(s) - Danger!",
    1736: "Vehicle(s) carrying hazardous materials - Danger!",
    1737: "Convoy(s) - Danger!",
    1738: "Military convoy(s) - Danger!",
    1739: "Overheight load(s) - Danger!",
    1740: "Abnormal load causing slow traffic - Delays",
    1741: "Convoy causing slow traffic - Delays",
    1751: "Abnormal load(s)",
    1752: "Wide load(s)",
    1753: "Long load(s)",
    1754: "Slow vehicle(s)",
    1755: "Convoy(s)",
    1756: "Abnormal load - Delays",
    1757: "Abnormal load - Delays expected",
    1758: "Abnormal load - Long delays",
    1759: "Convoy causing delays",
    1760: "Convoy - Delays expected",
    1761: "Convoy causing long delays",
    1762: "Exceptional load warning cleared",
    1763: "[Message cancelled]",
    1764: "Track-laying vehicle(s)",
    1765: "Vehicle(s) carrying hazardous materials",
    1766: "Military convoy(s)",
    1767: "Abnormal load(s) - No overtaking",
    1768: "Vehicles carrying hazardous materials have to stop at next safe place!",
    1769: "Hazardous load warning cleared",
    1770: "Convoy cleared",
    1771: "Warning cleared",
    1780: "Cancellations have to be expected",
    1781: "All services fully booked",
    1782: "Park and ride service will not be operating",
    1783: "Normal services will not be operating",
    1784: "Rail services will not be operating",
    1785: "Rapid transit service will not be operating",
    1786: "Underground service will not be operating",
    1787: "Public transport will be on strike",
    1788: "Ferry service will not be operating",
    1789: "Normal services expected",
    1790: "[Message cancelled]",
    1801: "Lane control signs not working",
    1802: "Emergency telephones not working",
    1803: "Emergency telephone number not working",
    1804: "Traffic lights not working",
    1805: "Traffic lights working incorrectly",
    1806: "Level crossing failure",
    1807: "Traffic lights not working - Stationary traffic",
    1808: "Traffic lights not working - Danger of stationary traffic!",
    1809: "Traffic lights not working - Queuing traffic",
    1810: "Traffic lights not working - Danger of queuing traffic!",
    1811: "Traffic lights not working - Slow traffic",
    1812: "Traffic lights not working - Slow traffic expected",
    1813: "Traffic lights not working - Heavy traffic",
    1814: "Traffic lights not working - Heavy traffic expected",
    1815: "Traffic lights not working - Traffic flowing freely",
    1816: "Traffic lights not working - Traffic building up",
    1817: "Traffic lights not working - Delays",
    1818: "Traffic lights not working - Delays expected",
    1819: "Traffic lights not working - Long delays",
    1820: "Level crossing failure - Stationary traffic",
    1821: "Level crossing failure - Danger of stationary traffic!",
    1822: "Level crossing failure - Queuing traffic",
    1823: "Level crossing failure - Danger of queuing traffic!",
    1824: "Level crossing failure - Slow traffic",
    1825: "Level crossing failure - Slow traffic expected",
    1826: "Level crossing failure - Heavy traffic",
    1827: "Level crossing failure - Heavy traffic expected",
    1828: "Level crossing failure - Traffic flowing freely",
    1829: "Level crossing failure - Traffic building up",
    1830: "Level crossing failure - Delays",
    1831: "Level crossing failure - Delays expected",
    1832: "Level crossing failure - Long delays",
    1833: "Electronic signs repaired",
    1834: "Emergency call facilities restored",
    1835: "Traffic signals repaired",
    1836: "Level crossing now working normally",
    1837: "[Message cancelled]",
    1838: "Lane control signs working incorrectly",
    1839: "Lane control signs operating",
    1840: "Variable message signs not working",
    1841: "Variable message signs working incorrectly",
    1842: "Variable message signs operating",
    1843: "Ramp control signals not working",
    1844: "Ramp control signals working incorrectly",
    1845: "Temporary traffic lights not working",
    1846: "Temporary traffic lights working incorrectly",
    1847: "Traffic signal control computer not working",
    1848: "Traffic signal timings changed",
    1849: "Tunnel ventilation not working",
    1850: "Lane control signs not working - Danger!",
    1851: "Temporary width limit",
    1852: "Temporary width limit lifted",
    1854: "Traffic regulations have been changed",
    1855: "Less than 50 parking spaces available",
    1856: "No parking information available",
    1857: "[Message cancelled]",
    1858: "Snowplough - Delays",
    1861: "Temporary height limit",
    1862: "Temporary height limit lifted",
    1863: "Automatic payment lanes not working",
    1864: "Lane control signs working incorrectly - Danger!",
    1865: "Emergency telephones out of order - Extra police patrols in operation",
    1866: "Emergency telephones out of order - In emergency, wait for police patrol",
    1867: "Traffic lights not working - Danger!",
    1868: "Traffic lights working incorrectly - Delays",
    1869: "Traffic lights working incorrectly - Delays expected",
    1870: "Traffic lights working incorrectly - Long delays",
    1871: "Temporary axle load limit",
    1872: "Temporary gross weight limit",
    1873: "Temporary gross weight limit lifted",
    1874: "Temporary axle weight limit lifted",
    1875: "Traffic lights working incorrectly - Danger!",
    1876: "Temporary traffic lights not working - Delays",
    1877: "Temporary traffic lights not working - Delays expected",
    1878: "Temporary traffic lights not working - Long delays",
    1879: "Temporary traffic lights not working - Danger!",
    1880: "Traffic signal control computer not working - Delays",
    1881: "Temporary length limit",
    1882: "Temporary length limit lifted",
    1883: "[Message cancelled]",
    1884: "Traffic signal control computer not working - Delays expected",
    1885: "Traffic signal control computer not working - Long delays",
    1886: "Normal parking restrictions lifted",
    1887: "Special parking restrictions in force",
    1888: "Parking - Percentage of spaces used: 10% full",
    1889: "Parking - Percentage of spaces used: 20% full",
    1890: "Parking - Percentage of spaces used: 30% full",
    1891: "Parking - Percentage of spaces used: 40% full",
    1892: "Parking - Percentage of spaces used: 50% full",
    1893: "Parking - Percentage of spaces used: 60% full",
    1894: "Parking - Percentage of spaces used: 70% full",
    1895: "Parking - Percentage of spaces used: 80% full",
    1896: "Parking - Percentage of spaces used: 90% full",
    1897: "Parking - Number of available spaces: Less than 10",
    1898: "Parking - Number of available spaces: Less than 20",
    1899: "Parking - Number of available spaces: Less than 30",
    1900: "Parking - Number of available spaces: Less than 40",
    1901: "Next departure [+ Extra information indicated]",
    1902: "Next departure for heavy vehicles [+ Extra information indicated]",
    1903: "Car park full",
    1904: "All car parks full",
    1905: "Less than car parking spaces available",
    1906: "Park and ride service operating",
    1907: "[null event - description is incomplete]",
    1908: "Switch your car radio to [Frequency mentioned]",
    1909: "Alarm call - important new information on this frequency follows now in normal programme",
    1910: "Alarm set - new information will be broadcast between these times in normal programme",
    1911: "[Message cancelled]",
    1913: "Switch your car radio to [Frequency mentioned]",
    1914: "No information available",
    1915: "This message is for test purposes only - please ignore",
    1916: "No information available due to technical problems",
    1917: "Automatic toll system not working - pay manually",
    1918: "Full",
    1920: "Only a few parking spaces available",
    1921: "Parking spaces available",
    1922: "Expect car park to be full",
    1923: "Expect no parking spaces available",
    1924: "Multi story car parks full",
    1925: "No problems to report with park and ride services",
    1926: "No parking spaces available",
    1927: "No parking",
    1928: "Special parking restrictions lifted",
    1929: "Urgent information will be given on normal programme broadcasts",
    1930: "This TMC service is not active",
    1931: "Detailed information will be given on normal programme broadcasts",
    1932: "Detailed information is provided by another TMC service",
    1934: "No park and ride information available",
    1938: "Park and ride information service resumed",
    1939: "Travel information telephone service availiable",
    1940: "Additional regional information is provided by another TMC service",
    1941: "Additional local information is provided by another TMC service",
    1942: "Additional public transport information is provided by another TMC service",
    1943: "National traffic information is provided by another TMC service",
    1944: "This TMC service provides major road information",
    1945: "This TMC service provides regional travel information",
    1946: "This TMC service provides local travel information",
    1947: "No detailed regional information provided by this service",
    1948: "No detailed local information provided by this service",
    1949: "No cross-border information provided by this service",
    1950: "Information restricted to this area",
    1951: "No new traffic information available",
    1952: "No public transport information available",
    1953: "This TMC service is being suspended",
    1954: "Active TMC service will resume",
    1955: "Reference to audio programmes no longer valid",
    1956: "Reference to other TMC services no longer valid",
    1957: "Previous announcement about this or other TMC services no longer valid",
    1961: "Allow emergency vehicles to pass in the carpool lane",
    1962: "Carpool lane available for all vehicles",
    1963: "Police directing traffic via the carpool lane",
    1964: "Rail information service not available",
    1965: "Rail information service resumed",
    1966: "Rapid transit information service not available",
    1967: "Rapid transit information service resumed",
    1971: "Police directing traffic",
    1972: "Buslane available for all vehicles",
    1973: "Police directing traffic via the buslane",
    1974: "Allow emergency vehicles to pass",
    1975: "Overtaking prohibited for heavy vehicles",
    1976: "Overtaking prohibited",
    1977: "Allow emergency vehicles to pass in the heavy vehicle lane",
    1978: "Heavy vehicle lane available for all vehicles",
    1979: "Police directing traffic via the heavy vehicle lane",
    1980: "Overtaking prohibited for heavy lorries",
    1981: "Drivers of heavy lorries are recommended to stop at next safe place",
    1982: "Buslane closed",
    1983: "Power failure",
    1985: "Overtaking restriction lifted",
    1986: "Low Emission Zone restriction in force",
    1990: "Car park closed",
    1991: "Danger of waiting vehicles on roadway!",
    1993: "Number of parking spaces decreasing",
    1994: "Number of parking spaces constant",
    1995: "Number of parking spaces increasing",
    1998: "Dangerous situation on exit slip road!",
    1999: "Dangerous situation on entry slip road!",
    2000: "Road/highway closed due to smog alert",
    2006: "Road/highway closed for vehicles with less than three occupants",
    2007: "Road/highway closed for vehicles with only one occupant",
    2013: "Service area busy",
    2021: "Service not operating, substitute service available",
    2022: "Public transport strike",
    2028: "[Message cancelled]",
    2029: "[Message cancelled]",
    2030: "[Message cancelled]",
    2032: "[Message cancelled]",
    2033: "[Message cancelled]",
    2034: "[Message cancelled]",
    2035: "[Message cancelled]",
    2038: "[Message cancelled]",
    2039: "[Message cancelled]",
    2040: "[Message cancelled]",
    2041: "Nothing to report",
    2042: "Ice build-up on cable structure",
    2043: "Road salted",
    2044: "Danger of snow patches!",
    2045: "Snow patches",
    2046: "Convoy service required due to bad weather"
};

export const INITIAL_RDS_DATA: RdsData = {
  pi: "----",
  ps: "--------",
  longPs: "",
  rtA: "",
  rtB: "",
  textAbFlag: false,
  rtPlus: [],
  rtPlusItemRunning: false,
  rtPlusItemToggle: false,
  hasOda: false,
  odaApp: undefined,
  odaList: [],
  hasRtPlus: false,
  hasEon: false,
  hasTmc: false,
  pty: 0,
  ptyName: "",
  ptyn: "",
  af: [],
  afListHead: null,
  afBLists: {}, 
  afType: 'Unknown',
  tp: false,
  ta: false,
  ms: false, 
  stereo: false, 
  artificialHead: false,
  compressed: false,
  dynamicPty: false,
  ecc: "",
  lic: "",
  pin: "",
  localTime: "",
  utcTime: "",
  eonData: {},
  tmcServiceInfo: { ltn: 0, sid: 0, afi: false, mode: 0, providerName: "[Unavailable]" },
  tmcMessages: [],
  ber: 0,
  rssi: 0,
  snr: 0,
  groupCounts: {},
  groupTotal: 0,
  groupSequence: [],
  recentGroups: [],
  psHistory: [],
  rtHistory: []
};

// ECC + PI First Char -> Country Mapping
export const ECC_COUNTRY_MAP: Record<string, Record<string, string>> = {
  "E0": {
    "9": "Albania", "3": "Andorra", "A": "Austria", "8": "Azores / Palestine", "6": "Belgium",
    "E": "Canary Islands", "D": "Germany", "1": "Germany", "B": "Hungary", "5": "Italy",
    "C": "Malta", "7": "Russia", "F": "Egypt", "2": "Algeria", "4": "Israel"
  },
  "E1": {
    "8": "Bulgaria", "2": "Cyprus", "9": "Denmark / Faroe Islands", "F": "France",
    "A": "Gibraltar", "1": "Greece", "7": "Luxembourg", "E": "Romania", "3": "San Marino",
    "4": "Switzerland", "C": "United Kingdom", "D": "Libya", "B": "Iraq", "5": "Jordan"
  },
  "E2": {
    "2": "Czech Republic", "A": "Iceland", "9": "Liechtenstein", "C": "Lithuania", "8": "Madeira",
    "B": "Monaco", "F": "Norway", "3": "Poland", "D": "Serbia", "5": "Slovakia",
    "E": "Spain", "4": "Vatican", "1": "Morocco", "7": "Tunisia", "6": "Syria"
  },
  "E3": {
    "F": "Belarus", "C": "Croatia", "2": "Ireland", "9": "Latvia", "1": "Montenegro",
    "8": "Netherlands", "E": "Sweden", "3": "Turkey", "B": "Azerbaijan", "D": "Kazakhstan",
    "A": "Lebanon", "5": "Tajikistan"
  },
  "E4": {
    "F": "Bosnia-Herzegovina", "2": "Estonia", "7": "Kosovo", "1": "Moldova",
    "3": "North Macedonia / Kyrgyzstan", "8": "Portugal", "9": "Slovenia", "6": "Ukraine",
    "A": "Armenia", "C": "Georgia", "E": "Turkmenistan", "B": "Uzbekistan"
  },
  "D0": {
    "6": "Angola", "E": "Benin", "B": "Burkina Faso", "1": "Cameroon", "2": "Central African Republic",
    "3": "Djibouti", "7": "Equatorial Guinea", "8": "Gabon", "9": "Guinea", "4": "Madagascar",
    "F": "Malawi", "5": "Mali", "C": "Republic of the Congo", "A": "South Africa", "D": "Togo"
  },
  "D1": {
    "A": "Ascension Island", "B": "Botswana", "9": "Burundi", "6": "Cape Verde", "C": "Comoros",
    "E": "Ethiopia", "8": "Gambia", "3": "Ghana", "2": "Liberia", "4": "Mauritania",
    "F": "Nigeria", "1": "Namibia", "5": "Sao Tome and Principe", "7": "Senegal", "D": "Tanzania"
  },
  "D2": {
    "9": "Chad", "B": "Democratic Republic of the Congo", "5": "Eswatini", "A": "Guinea-Bissau",
    "C": "Ivory Coast", "6": "Kenya", "3": "Mozambique", "8": "Niger", "1": "Sierra Leone",
    "4": "Uganda", "E": "Zambia", "D": "Zanzibar", "2": "Zimbabwe"
  },
  "D3": {
    "6": "Lesotho", "A": "Mauritius", "5": "Rwanda", "8": "Seychelles", "C": "Sudan",
    "3": "Western Sahara"
  },
  "A2": {
    "1": "Anguilla", "2": "Antigua and Barbuda", "A": "Argentina", "F": "Bahamas", "5": "Barbados",
    "6": "Belize", "C": "Bermuda", "B": "Brazil", "7": "Cayman Islands", "8": "Costa Rica",
    "9": "Cuba", "3": "Ecuador", "4": "Falkland Islands", "E": "Guadeloupe", "D": "Netherlands Antilles"
  },
  "A4": {
    "3": "Aruba", "C": "El Salvador", "1": "Guatemala", "D": "Haiti", "2": "Honduras",
    "F": "Mexico", "5": "Montserrat", "7": "Peru", "A": "Saint Kitts and Nevis", "B": "Saint Lucia",
    "8": "Suriname", "6": "Trinidad and Tobago", "9": "Uruguay", "E": "Venezuela"
  },
  "A3": {
    "1": "Bolivia", "C": "Chile", "2": "Colombia", "A": "Dominica", "B": "Dominican Republic",
    "D": "Grenada", "F": "Guyana", "3": "Jamaica", "4": "Martinique", "7": "Nicaragua",
    "9": "Panama", "6": "Paraguay", "8": "Puerto Rico", "E": "Turks and Caicos Islands"
  },
  "A1": {
    "C": "Canada", "F": "Greenland"
  },
  "A5": {
    "C": "Saint Vincent and the Grenadines", "F": "Virgin Islands"
  },
  "A6": {
    "F": "Saint Pierre and Miquelon"
  },
  "A0": {
    "1": "United States of America", "2": "United States of America", "3": "United States of America",
    "4": "United States of America", "5": "United States of America", "6": "United States of America",
    "7": "United States of America", "8": "United States of America", "9": "United States of America",
    "A": "United States of America", "B": "United States of America", "D": "United States of America",
    "E": "United States of America"
  },
  "F0": {
    "A": "Afghanistan", "1": "Australia", "2": "Australia", "3": "Australia", "4": "Australia",
    "5": "Australia", "6": "Australia", "7": "Australia", "8": "Australia", "E": "Bahrain",
    "C": "China", "F": "Malaysia", "B": "Myanmar", "D": "North Korea", "9": "Saudi Arabia"
  },
  "F1": {
    "3": "Bangladesh", "2": "Bhutan", "B": "Brunei", "5": "Fiji", "F": "Hong Kong",
    "8": "Iran", "1": "Kiribati", "7": "Nauru", "9": "New Zealand", "6": "Oman",
    "4": "Pakistan", "A": "Solomon Islands", "E": "South Korea", "C": "Sri Lanka", "D": "Taiwan"
  },
  "F2": {
    "3": "Cambodia", "5": "India", "C": "Indonesia", "9": "Japan", "1": "Kuwait",
    "6": "Macau", "B": "Maldives", "E": "Nepal", "8": "Philippines", "2": "Qatar",
    "4": "Samoa", "A": "Singapore", "D": "United Arab Emirates", "7": "Vietnam", "F": "Vanuatu"
  },
  "F3": {
    "1": "Laos", "E": "Micronesia", "F": "Mongolia", "9": "Papua New Guinea", "2": "Thailand",
    "3": "Tonga", "B": "Yemen"
  }
};

// LIC -> Language Mapping
export const LIC_LANGUAGE_MAP: Record<string, string> = {
    "01": "Albanian", "02": "Breton", "03": "Catalan", "04": "Croatian",
    "05": "Welsh", "06": "Czech", "07": "Danish", "08": "German", "09": "English",
    "0A": "Spanish", "0B": "Esperanto", "0C": "Estonian", "0D": "Basque", "0E": "Faroese",
    "0F": "French", "10": "Frisian", "11": "Irish", "12": "Gaelic", "13": "Galician",
    "14": "Icelandic", "15": "Italian", "16": "Sami", "17": "Latin", "18": "Latvian",
    "19": "Luxembourgian", "1A": "Lithuanian", "1B": "Hungarian", "1C": "Maltese", "1D": "Dutch",
    "1E": "Norwegian", "1F": "Occitan", "20": "Polish", "21": "Portuguese", "22": "Romanian",
    "23": "Romansh", "24": "Serbian", "25": "Slovak", "26": "Slovenian", "27": "Finnish",
    "28": "Swedish", "29": "Turkish", "2A": "Flemish", "2B": "Walloon",
    "7F": "Amharic", "7E": "Arabic", "7D": "Armenian", "7C": "Assamese", "7B": "Azerbaijani",
    "7A": "Bambara", "79": "Belarusian", "78": "Bengali", "77": "Bulgarian", "76": "Burmese",
    "75": "Chinese", "74": "Chuvash", "73": "Dari", "72": "Fulani", "71": "Georgian", "70": "Greek",
    "6F": "Gujarati", "6E": "Gorani", "6D": "Hausa", "6C": "Hebrew", "6B": "Hindi", "6A": "Indonesian",
    "69": "Japanese", "68": "Kannada", "67": "Kazakh", "66": "Khmer", "65": "Korean", "64": "Laotian",
    "63": "Macedonian", "62": "Malagasy", "61": "Malaysian", "60": "Moldovan", "5F": "Marathi",
    "5E": "Ndebele", "5D": "Nepali", "5C": "Oriya", "5B": "Papiamento", "5A": "Persian", "59": "Punjabi",
    "58": "Pushtu", "57": "Quechua", "56": "Russian", "55": "Rusyn", "54": "Serbo-Croat", "53": "Shona",
    "52": "Sinhalese", "51": "Somali", "50": "Sranan Tongo", "4F": "Swahili", "4E": "Tadzhik",
    "4D": "Tamil", "4C": "Tatar", "4B": "Telugu", "4A": "Thai", "49": "Ukrainian", "48": "Urdu",
    "47": "Uzbek", "46": "Vietnamese", "45": "Zulu"
};
